version: "3.9"

services:
  app:
    container_name: pdf-api-app
    build:
      context: .
      dockerfile: Dockerfile
    image: pdf-api
    ports:
      - "3002:3000"
    env_file:
      - .env
    environment:
      PUPPETEER_SKIP_DOWNLOAD: true
      PYTHON_SERVICE_URL: http://python-service:5000/generate-zugferd
    cap_add:
      - SYS_ADMIN
    depends_on:
      - mongo
      - python-service
    networks:
      - pdfnet

  mongo:
    container_name: pdf-api-mongo
    image: mongo:5.0
    volumes:
      - ./mongo-data:/data/db
    networks:
      - pdfnet

  python-service:
    container_name: python-service
    build:
      context: ./python-service
    image: pdf-api-python
    volumes:
      - ./python-service:/app
    restart: unless-stopped
    networks:
      - pdfnet

volumes:
  mongo-data:

networks:
  pdfnet:
    driver: bridge
