services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pdf-api
    ports:
      - "3002:3000"
    env_file:
      - .env
    environment:
      PUPPETEER_SKIP_DOWNLOAD: true
    cap_add:
      - SYS_ADMIN
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    container_name: pdf-api-mongo
    volumes:
      - ./mongo-data:/data/db

volumes:
  mongo-data: