# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e07548c088f572af4bbf103e4dee46bb"
name = "PDFify Pro"
application_url = "https://pdfify.pro/"
embedded = true

[webhooks]
api_version = "2026-01"
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://pdfify.pro/webhook/app-uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "https://pdfify.pro/webhook/order-created"

  [[webhooks.subscriptions]]
  topics = [ "customers/redact" ]
  uri = "https://pdfify.pro/webhook/customers-redact"

  [[webhooks.subscriptions]]
  topics = [ "customers/data_request" ]
  uri = "https://pdfify.pro/webhook/customers-data-request"

  [[webhooks.subscriptions]]
  topics = [ "shop/redact" ]
  uri = "https://pdfify.pro/webhook/shop-redact"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_locations,read_orders,read_products,read_themes"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://pdfify.pro/api/shopify/callback" ]

[pos]
embedded = false
