const { format } = require("date-fns");

function escapeXml(unsafe) {
  if (!unsafe) return "";
  return unsafe.replace(/[<>&'"]/g, (c) => {
    switch (c) {
      case "<": return "&lt;";
      case ">": return "&gt;";
      case "&": return "&amp;";
      case "'": return "&apos;";
      case '"': return "&quot;";
      default: return c;
    }
  });
}

/**
 * Generate ZUGFeRD/EN16931 XML for PDF/A-3b embedding
 * @param {Object} data - Invoice data
 * @param {string} compliance - "BASIC" or "EN16931"
 * @returns {string} XML string
 */
function generateZugferdXML(data, compliance = "BASIC") {
  const now = new Date();
  const invoiceDate = data.date ? new Date(data.date) : now;

  const fmtDate = (date) => format(date, "yyyy-MM-dd");
  const fmtAmount = (num) => Number(num).toFixed(2);
  const vatRate = data.vatRate !== undefined ? Number(data.vatRate) : 21;

  const subtotal = fmtAmount(
    data.subtotal ??
      data.items?.reduce((acc, i) => acc + (i.price * (i.quantity ?? 1) || 0), 0) ?? 0
  );
  const tax = fmtAmount(data.tax ?? ((parseFloat(subtotal) * vatRate) / 100));
  const total = fmtAmount(data.total ?? (parseFloat(subtotal) + parseFloat(tax)));

  const guideline = compliance === "EN16931"
    ? "urn:cen.eu:en16931:2017"
    : "urn:ferd:CrossIndustryDocument:invoice:2p1:basic";

  // Payment terms
  const paymentTerms = data.paymentTerms || "Payment due within 14 days";

  return `<?xml version="1.0" encoding="UTF-8"?>
<rsm:CrossIndustryInvoice
  xmlns:rsm="urn:ferd:CrossIndustryDocument:invoice:2p1"
  xmlns:ram="urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12"
  xmlns:qdt="urn:un:unece:uncefact:data:standard:QualifiedDataType:12"
  xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:15"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <rsm:ExchangedDocumentContext>
    <ram:GuidelineSpecifiedDocumentContextParameter>
      <ram:ID>${guideline}</ram:ID>
    </ram:GuidelineSpecifiedDocumentContextParameter>
  </rsm:ExchangedDocumentContext>

  <rsm:ExchangedDocument>
    <ram:ID>${escapeXml(data.orderId || "INV-0001")}</ram:ID>
    <ram:TypeCode>380</ram:TypeCode>
    <ram:IssueDateTime>
      <udt:DateTimeString format="102">${fmtDate(invoiceDate).replace(/-/g, "")}</udt:DateTimeString>
    </ram:IssueDateTime>
    <ram:IncludedNote>
      <ram:Content>Invoice generated by PDFify (${compliance})</ram:Content>
    </ram:IncludedNote>
  </rsm:ExchangedDocument>

  <rsm:SupplyChainTradeTransaction>
    <ram:ApplicableHeaderTradeAgreement>
      <ram:SellerTradeParty>
        <ram:Name>${escapeXml(data.sellerName || "Your Company")}</ram:Name>
        <ram:PostalTradeAddress>
          <ram:LineOne>${escapeXml(data.sellerAddress || "Address")}</ram:LineOne>
          <ram:CityName>${escapeXml(data.sellerCity || "City")}</ram:CityName>
          <ram:PostcodeCode>${escapeXml(data.sellerPostcode || "00000")}</ram:PostcodeCode>
          <ram:CountryID>${escapeXml(data.sellerCountry || "DE")}</ram:CountryID>
        </ram:PostalTradeAddress>
        <ram:SpecifiedTaxRegistration>
          <ram:ID schemeID="FC">${escapeXml(data.sellerTaxId || "DE123456789")}</ram:ID>
        </ram:SpecifiedTaxRegistration>
        <ram:SpecifiedTradeSettlementPaymentMeans>
          <ram:TypeCode>31</ram:TypeCode> <!-- Bank transfer -->
          <ram:Information>IBAN: ${escapeXml(data.sellerIBAN || "DE12345678901234567890")} BIC: ${escapeXml(data.sellerBIC || "DEUTDEFF")}</ram:Information>
        </ram:SpecifiedTradeSettlementPaymentMeans>
      </ram:SellerTradeParty>

      <ram:BuyerTradeParty>
        <ram:Name>${escapeXml(data.customerName || "Customer")}</ram:Name>
        <ram:PostalTradeAddress>
          <ram:LineOne>${escapeXml(data.customerAddress || "Address")}</ram:LineOne>
          <ram:CityName>${escapeXml(data.customerCity || "City")}</ram:CityName>
          <ram:PostcodeCode>${escapeXml(data.customerPostcode || "00000")}</ram:PostcodeCode>
          <ram:CountryID>${escapeXml(data.customerCountry || "DE")}</ram:CountryID>
        </ram:PostalTradeAddress>
      </ram:BuyerTradeParty>
    </ram:ApplicableHeaderTradeAgreement>

    <ram:ApplicableHeaderTradeSettlement>
      <ram:InvoiceCurrencyCode>${escapeXml(data.currency || "EUR")}</ram:InvoiceCurrencyCode>
      <ram:ApplicableTradeTax>
        <ram:TypeCode>VAT</ram:TypeCode>
        <ram:CategoryCode>S</ram:CategoryCode>
        <ram:RateApplicablePercent>${vatRate}</ram:RateApplicablePercent>
        <ram:CalculatedAmount currencyID="${escapeXml(data.currency || "EUR")}">${tax}</ram:CalculatedAmount>
      </ram:ApplicableTradeTax>
      <ram:SpecifiedTradeSettlementMonetarySummation>
        <ram:LineTotalAmount currencyID="${escapeXml(data.currency || "EUR")}">${subtotal}</ram:LineTotalAmount>
        <ram:TaxTotalAmount currencyID="${escapeXml(data.currency || "EUR")}">${tax}</ram:TaxTotalAmount>
        <ram:GrandTotalAmount currencyID="${escapeXml(data.currency || "EUR")}">${total}</ram:GrandTotalAmount>
      </ram:SpecifiedTradeSettlementMonetarySummation>
      <ram:ApplicableTradePaymentTerms>
        <ram:Description>${escapeXml(paymentTerms)}</ram:Description>
      </ram:ApplicableTradePaymentTerms>
    </ram:ApplicableHeaderTradeSettlement>

    ${data.items?.map((item, idx) => `
      <ram:IncludedSupplyChainTradeLineItem>
        <ram:AssociatedDocumentLineDocument>
          <ram:LineID>${idx + 1}</ram:LineID>
          <ram:IncludedNote>
            <ram:Content>${escapeXml(item.description || item.name || "Item description")}</ram:Content>
          </ram:IncludedNote>
        </ram:AssociatedDocumentLineDocument>
        <ram:SpecifiedTradeProduct>
          <ram:Name>${escapeXml(item.name || "Product")}</ram:Name>
        </ram:SpecifiedTradeProduct>
        <ram:SpecifiedLineTradeAgreement>
          <ram:GrossPriceProductTradePrice>
            <ram:ChargeAmount currencyID="${escapeXml(data.currency || "EUR")}">${fmtAmount(item.price || 0)}</ram:ChargeAmount>
          </ram:GrossPriceProductTradePrice>
        </ram:SpecifiedLineTradeAgreement>
        <ram:SpecifiedLineTradeDelivery>
          <ram:BilledQuantity unitCode="${escapeXml(item.unit || "C62")}">${item.quantity ?? 1}</ram:BilledQuantity>
        </ram:SpecifiedLineTradeDelivery>
        <ram:SpecifiedLineTradeSettlement>
          <ram:ApplicableTradeTax>
            <ram:TypeCode>VAT</ram:TypeCode>
            <ram:CategoryCode>S</ram:CategoryCode>
            <ram:RateApplicablePercent>${vatRate}</ram:RateApplicablePercent>
            <ram:CalculatedAmount currencyID="${escapeXml(data.currency || "EUR")}">${fmtAmount((item.price || 0) * (item.quantity ?? 1) * (vatRate / 100))}</ram:CalculatedAmount>
          </ram:ApplicableTradeTax>
          <ram:TradeSettlementLineAmount currencyID="${escapeXml(data.currency || "EUR")}">${fmtAmount((item.price || 0) * (item.quantity ?? 1))}</ram:TradeSettlementLineAmount>
        </ram:SpecifiedLineTradeSettlement>
      </ram:IncludedSupplyChainTradeLineItem>
    `).join("")}

  </rsm:SupplyChainTradeTransaction>
</rsm:CrossIndustryInvoice>`;
}

module.exports = { generateZugferdXML };
