name: Deploy to Server

# Trigger the workflow on push events to the main branch
on:
  push:
    branches:
      - main # Or your default/production branch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest # Use a standard GitHub runner to execute the SSH command

    steps:
    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@v1.0.3 # Or use a specific tagged version
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        # port: 22 # Optional, defaults to 22
        script: |
          echo "Connecting to server..."
          cd ${{ secrets.SERVER_APP_PATH }}
          echo "Changed directory to $(pwd)"
          echo "Stopping containers..."
          docker compose down
          echo "Pulling latest changes..."
          git pull
          echo "Building and starting containers..."
          docker compose up -d --build
          echo "Deployment complete!"
          # Optional: Prune old images/containers
          # docker system prune -af